language: julia

os:
    - linux

julia:
    - 1.1

matrix:
    allow_failures:
        - julia: nightly

notifications:
    email: false

before_install:
    # If it is linux, we must install `libncurses`.
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ls -la /usr/lib/x86_64-linux-gnu/libncurses*;     fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo cat /usr/lib/x86_64-linux-gnu/libncurses.so;      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libncurses5     libncursesw5;     fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libncurses5-dev libncursesw5-dev; fi

after_success:
    # Push coverage results to Coveralls.
    - julia -e 'import Pkg; cd(Pkg.dir("TextUserInterfaces")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
    # Push coverage results to Codecov.
    - julia -e 'import Pkg; cd(Pkg.dir("TextUserInterfaces")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
